
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUMARESTAleftMULTIPLICACIONDIVISIONDIVISIONErightNEGATIVOleftPARENTESISIPARENTESISDASIGNACION BLINK BOOL CALL COMA COMENTARIO COMPARACION CUBO DEL DELAY DIMCOLUMNAS DIMFILAS DISTINTOQUE DIVISION DIVISIONE DOSPUNTOS EXPONENCIAL F FALSE FOR ID0 ID1 ID2 IN INSERT LEN LIST LLAVED LLAVEI MAIN MAYORIGUALQUE MAYORQUE MENORIGUALQUE MENORQUE MIL MIN MODULO MULTIPLICACION NEG NEGATIVO NUMERO PARENTESISCD PARENTESISCI PARENTESISD PARENTESISI PROCEDURE PUNTO PUNTOCOMA RANGE RANGOTIMER RESTA SEG SHAPEA SHAPEC SHAPEF STEP SUMA T TIMER TRUE TYPEexpression : expression SUMA termexpression : expression RESTA termterm : term MULTIPLICACION factorterm : term DIVISION factorterm : term DIVISIONE factorterm : term MODULO factorterm : term EXPONENCIAL factorexpression : RESTA term %prec NEGATIVOexpression : termterm : factorfactor : NUMEROfactor : ID0factor : ID0 PARENTESISCI NUMERO PARENTESISCDfactor : PARENTESISI expression PARENTESISDempty :'
    
_lr_action_items = {'RESTA':([0,1,2,4,5,6,7,15,17,18,19,20,21,22,23,24,26,27,],[3,9,-9,-10,-11,-12,3,-8,9,-1,-2,-3,-4,-5,-6,-7,-14,-13,]),'NUMERO':([0,3,7,8,9,10,11,12,13,14,16,],[5,5,5,5,5,5,5,5,5,5,25,]),'ID0':([0,3,7,8,9,10,11,12,13,14,],[6,6,6,6,6,6,6,6,6,6,]),'PARENTESISI':([0,3,7,8,9,10,11,12,13,14,],[7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[0,-9,-10,-11,-12,-8,-1,-2,-3,-4,-5,-6,-7,-14,-13,]),'SUMA':([1,2,4,5,6,15,17,18,19,20,21,22,23,24,26,27,],[8,-9,-10,-11,-12,-8,8,-1,-2,-3,-4,-5,-6,-7,-14,-13,]),'PARENTESISD':([2,4,5,6,15,17,18,19,20,21,22,23,24,26,27,],[-9,-10,-11,-12,-8,26,-1,-2,-3,-4,-5,-6,-7,-14,-13,]),'MULTIPLICACION':([2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[10,-10,-11,-12,10,10,10,-3,-4,-5,-6,-7,-14,-13,]),'DIVISION':([2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[11,-10,-11,-12,11,11,11,-3,-4,-5,-6,-7,-14,-13,]),'DIVISIONE':([2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[12,-10,-11,-12,12,12,12,-3,-4,-5,-6,-7,-14,-13,]),'MODULO':([2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[13,-10,-11,-12,13,13,13,-3,-4,-5,-6,-7,-14,-13,]),'EXPONENCIAL':([2,4,5,6,15,18,19,20,21,22,23,24,26,27,],[14,-10,-11,-12,14,14,14,-3,-4,-5,-6,-7,-14,-13,]),'PARENTESISCI':([6,],[16,]),'PARENTESISCD':([25,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,],[1,17,]),'term':([0,3,7,8,9,],[2,15,2,18,19,]),'factor':([0,3,7,8,9,10,11,12,13,14,],[4,4,4,4,4,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression SUMA term','expression',3,'p_expression_suma','OperacionesMatematicas.py',18),
  ('expression -> expression RESTA term','expression',3,'p_expression_resta','OperacionesMatematicas.py',23),
  ('term -> term MULTIPLICACION factor','term',3,'p_term_multiplicacion','OperacionesMatematicas.py',28),
  ('term -> term DIVISION factor','term',3,'p_term_division','OperacionesMatematicas.py',33),
  ('term -> term DIVISIONE factor','term',3,'p_term_divisione','OperacionesMatematicas.py',37),
  ('term -> term MODULO factor','term',3,'p_term_modulo','OperacionesMatematicas.py',41),
  ('term -> term EXPONENCIAL factor','term',3,'p_term_exponencial','OperacionesMatematicas.py',45),
  ('expression -> RESTA term','expression',2,'p_expression_negativo','OperacionesMatematicas.py',49),
  ('expression -> term','expression',1,'p_expression_term','OperacionesMatematicas.py',56),
  ('term -> factor','term',1,'p_term_factor','OperacionesMatematicas.py',61),
  ('factor -> NUMERO','factor',1,'p_factor_num','OperacionesMatematicas.py',66),
  ('factor -> ID0','factor',1,'p_factor_ID','OperacionesMatematicas.py',71),
  ('factor -> ID0 PARENTESISCI NUMERO PARENTESISCD','factor',4,'p_factor_array','OperacionesMatematicas.py',83),
  ('factor -> PARENTESISI expression PARENTESISD','factor',3,'p_factor_expr','OperacionesMatematicas.py',96),
  ('empty -> <empty>','empty',0,'p_empty','OperacionesMatematicas.py',101),
]
